# Generated by Django 2.2.3 on 2019-07-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Self',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.IntegerField(default=15485863)),
                ('private_key', models.IntegerField(default=15485867)),
                ('df_key', models.IntegerField()),
            ],
        ),
    ]
